### ISSUE TITLE
ROS 2 port

### ISSUE THREAD

**Issue by dirk-thomas** [WPI-RAIL/async_web_server_cpp#11]
Similar to GT-RAIL/rosauth#16.

We would like to contribute a `ros2` branch to this repo. If you could provide me access (as for the `rosauth` repo) I would go ahead, create the branch as well as create the first PR targeting that branch. Thanks!

**Comment by rctoris** [comment]
branched and added as collaborator

**Comment by dirk-thomas** [comment]
Thank you!
