### ISSUE TITLE
Official Kinetic support?

### ISSUE THREAD

**Issue by nstiurca** [WPI-RAIL/async_web_server_cpp#7]
Hi,

I'm wondering if you have any plans for official ROS Kinetic support (ie, binaries). I was able to compile this code from source with absolutely 0 problems under Ubuntu 16.04 + ROS Kinetic.

Thanks.

**Comment by jihoonl** [comment]
Can we release this on kinetic? It blocks release of web_video_server. If necessary, I can take over the release process

**Comment by rctoris** [comment]
Sure, I can get to it later this week. I have a few others pending on my list as well.

**Comment by jack-oquin** [comment]
Thanks!

We depend on web_video_server, which needs this, xref: RobotWebTools/web_video_server#29.

**Comment by jack-oquin** [comment]
The `develop` branch does compile cleanly with Kinetic on Xenial.

**Comment by rctoris** [comment]
https://github.com/ros/rosdistro/pull/13453
